import type { PlantCatalog } from './types';

export const plantCatalogData: PlantCatalog = {
  version: 1,
  items: [
    { id: 'allium-cepa', latin: 'Allium cepa', common: ['onion', 'bulb onion'], syn: ['common onion'] },
    { id: 'allium-sativum', latin: 'Allium sativum', common: ['garlic'], syn: ['common garlic'] },
    { id: 'allium-schoenoprasum', latin: 'Allium schoenoprasum', common: ['chives'], syn: ['garden chives'] },
    { id: 'ananas-comosus', latin: 'Ananas comosus', common: ['pineapple'], syn: ['ananas'] },
    { id: 'anethum-graveolens', latin: 'Anethum graveolens', common: ['dill'], syn: ['dill weed'] },
    { id: 'anthurium-andraeanum', latin: 'Anthurium andraeanum', common: ['anthurium', 'flamingo flower'], syn: ['tailflower'] },
    { id: 'apium-graveolens', latin: 'Apium graveolens', common: ['celery'], syn: ['garden celery'] },
    { id: 'asparagus-officinalis', latin: 'Asparagus officinalis', common: ['asparagus'], syn: ['garden asparagus'] },
    { id: 'beta-vulgaris', latin: 'Beta vulgaris', common: ['beet', 'beetroot'], syn: ['red beet'] },
    { id: 'begonia-rex', latin: 'Begonia rex', common: ['rex begonia'], syn: ['painted-leaf begonia'] },
    { id: 'brassica-oleracea-var-botrytis', latin: 'Brassica oleracea var. botrytis', common: ['cauliflower'], syn: ['cauli'] },
    { id: 'brassica-oleracea-var-capitata', latin: 'Brassica oleracea var. capitata', common: ['cabbage'], syn: ['head cabbage'] },
    { id: 'brassica-oleracea-var-gemmifera', latin: 'Brassica oleracea var. gemmifera', common: ['brussels sprouts'], syn: ['sprouts'] },
    { id: 'brassica-oleracea-var-italica', latin: 'Brassica oleracea var. italica', common: ['broccoli'], syn: ['calabrese'] },
    { id: 'brassica-oleracea-var-sabellica', latin: 'Brassica oleracea var. sabellica', common: ['kale'], syn: ['leaf kale'] },
    { id: 'brassica-rapa-subsp-chinensis', latin: 'Brassica rapa subsp. chinensis', common: ['bok choy', 'pak choi'], syn: ['chinese cabbage'] },
    { id: 'brassica-rapa-subsp-pekinensis', latin: 'Brassica rapa subsp. pekinensis', common: ['napa cabbage'], syn: ['chinese napa'] },
    { id: 'calathea-ornata', latin: 'Calathea ornata', common: ['calathea', 'pinstripe calathea'], syn: ['goeppertia ornata'] },
    { id: 'camellia-sinensis', latin: 'Camellia sinensis', common: ['tea plant'], syn: ['tea'] },
    { id: 'cannabis-indica', latin: 'Cannabis indica', common: ['indica'], syn: ['c. indica'] },
    { id: 'cannabis-ruderalis', latin: 'Cannabis ruderalis', common: ['ruderalis'], syn: ['c. ruderalis'] },
    { id: 'cannabis-sativa', latin: 'Cannabis sativa', common: ['hemp', 'marijuana'], syn: ['c. sativa'] },
    { id: 'capsicum-annuum', latin: 'Capsicum annuum', common: ['bell pepper', 'sweet pepper'], syn: ['capsicum'] },
    { id: 'capsicum-chinense', latin: 'Capsicum chinense', common: ['habanero', 'ghost pepper'], syn: ['hot pepper'] },
    { id: 'carica-papaya', latin: 'Carica papaya', common: ['papaya'], syn: ['pawpaw'] },
    { id: 'chlorophytum-comosum', latin: 'Chlorophytum comosum', common: ['spider plant'], syn: ['ribbon plant'] },
    { id: 'citrullus-lanatus', latin: 'Citrullus lanatus', common: ['watermelon'], syn: ['melon'] },
    { id: 'citrus-limon', latin: 'Citrus limon', common: ['lemon'], syn: ['lemon tree'] },
    { id: 'citrus-paradisi', latin: 'Citrus paradisi', common: ['grapefruit'], syn: ['pomelo hybrid'] },
    { id: 'citrus-sinensis', latin: 'Citrus sinensis', common: ['orange'], syn: ['sweet orange'] },
    { id: 'coffea-arabica', latin: 'Coffea arabica', common: ['coffee plant'], syn: ['arabica coffee'] },
    { id: 'coriandrum-sativum', latin: 'Coriandrum sativum', common: ['cilantro', 'coriander'], syn: ['chinese parsley'] },
    { id: 'crassula-ovata', latin: 'Crassula ovata', common: ['jade plant'], syn: ['money tree jade'] },
    { id: 'cucumis-melo', latin: 'Cucumis melo', common: ['melon', 'cantaloupe'], syn: ['muskmelon'] },
    { id: 'cucumis-sativus', latin: 'Cucumis sativus', common: ['cucumber'], syn: ['garden cucumber'] },
    { id: 'daucus-carota', latin: 'Daucus carota', common: ['carrot'], syn: ['garden carrot'] },
    { id: 'dracaena-fragrans', latin: 'Dracaena fragrans', common: ['corn plant'], syn: ['dracaena'] },
    { id: 'epipremnum-aureum', latin: 'Epipremnum aureum', common: ['pothos', "devil's ivy"], syn: ['golden pothos'] },
    { id: 'ficus-carica', latin: 'Ficus carica', common: ['fig'], syn: ['common fig'] },
    { id: 'ficus-elastica', latin: 'Ficus elastica', common: ['rubber plant'], syn: ['rubber tree'] },
    { id: 'ficus-lyrata', latin: 'Ficus lyrata', common: ['fiddle-leaf fig'], syn: ['fiddle leaf'] },
    { id: 'fragaria-x-ananassa', latin: 'Fragaria × ananassa', common: ['strawberry'], syn: ['garden strawberry'] },
    { id: 'humulus-lupulus', latin: 'Humulus lupulus', common: ['hops'], syn: ['common hop'] },
    { id: 'ipomoea-batatas', latin: 'Ipomoea batatas', common: ['sweet potato'], syn: ['yam'] },
    { id: 'lactuca-sativa', latin: 'Lactuca sativa', common: ['lettuce'], syn: ['garden lettuce'] },
    { id: 'lavandula-angustifolia', latin: 'Lavandula angustifolia', common: ['lavender'], syn: ['english lavender'] },
    { id: 'malus-domestica', latin: 'Malus domestica', common: ['apple'], syn: ['apple tree'] },
    { id: 'mangifera-indica', latin: 'Mangifera indica', common: ['mango'], syn: ['mango tree'] },
    { id: 'mentha-piperita', latin: 'Mentha × piperita', common: ['peppermint'], syn: ['mint'] },
    { id: 'mentha-spicata', latin: 'Mentha spicata', common: ['spearmint'], syn: ['garden mint'] },
    { id: 'monstera-deliciosa', latin: 'Monstera deliciosa', common: ['monstera', 'swiss cheese plant'], syn: ['split-leaf philodendron'] },
    { id: 'musa-acuminata', latin: 'Musa acuminata', common: ['banana'], syn: ['banana plant'] },
    { id: 'nicotiana-tabacum', latin: 'Nicotiana tabacum', common: ['tobacco'], syn: ['cultivated tobacco'] },
    { id: 'ocimum-basilicum', latin: 'Ocimum basilicum', common: ['basil'], syn: ['sweet basil'] },
    { id: 'olea-europaea', latin: 'Olea europaea', common: ['olive'], syn: ['olive tree'] },
    { id: 'origanum-vulgare', latin: 'Origanum vulgare', common: ['oregano'], syn: ['wild marjoram'] },
    { id: 'pelargonium-x-hortorum', latin: 'Pelargonium × hortorum', common: ['geranium'], syn: ['zonal geranium'] },
    { id: 'persea-americana', latin: 'Persea americana', common: ['avocado'], syn: ['avocado tree'] },
    { id: 'petroselinum-crispum', latin: 'Petroselinum crispum', common: ['parsley'], syn: ['garden parsley'] },
    { id: 'phaseolus-vulgaris', latin: 'Phaseolus vulgaris', common: ['bean', 'green bean'], syn: ['common bean'] },
    { id: 'phalaenopsis-aphrodite', latin: 'Phalaenopsis aphrodite', common: ['moth orchid', 'orchid'], syn: ['phalaenopsis'] },
    { id: 'philodendron-hederaceum', latin: 'Philodendron hederaceum', common: ['heartleaf philodendron'], syn: ['philodendron'] },
    { id: 'pilea-peperomioides', latin: 'Pilea peperomioides', common: ['chinese money plant'], syn: ['pilea'] },
    { id: 'pisum-sativum', latin: 'Pisum sativum', common: ['pea'], syn: ['garden pea'] },
    { id: 'prunus-armeniaca', latin: 'Prunus armeniaca', common: ['apricot'], syn: ['apricot tree'] },
    { id: 'prunus-avium', latin: 'Prunus avium', common: ['sweet cherry', 'cherry'], syn: ['cherry tree'] },
    { id: 'prunus-domestica', latin: 'Prunus domestica', common: ['plum'], syn: ['plum tree'] },
    { id: 'prunus-persica', latin: 'Prunus persica', common: ['peach'], syn: ['peach tree'] },
    { id: 'psidium-guajava', latin: 'Psidium guajava', common: ['guava'], syn: ['apple guava'] },
    { id: 'punica-granatum', latin: 'Punica granatum', common: ['pomegranate'], syn: ['pomegranate tree'] },
    { id: 'pyrus-communis', latin: 'Pyrus communis', common: ['pear'], syn: ['pear tree'] },
    { id: 'rheum-rhabarbarum', latin: 'Rheum rhabarbarum', common: ['rhubarb'], syn: ['garden rhubarb'] },
    { id: 'rosmarinus-officinalis', latin: 'Rosmarinus officinalis', common: ['rosemary'], syn: ['salvia rosmarinus'] },
    { id: 'rubus-fruticosus', latin: 'Rubus fruticosus', common: ['blackberry'], syn: ['bramble'] },
    { id: 'rubus-idaeus', latin: 'Rubus idaeus', common: ['raspberry'], syn: ['red raspberry'] },
    { id: 'salvia-officinalis', latin: 'Salvia officinalis', common: ['sage'], syn: ['common sage'] },
    { id: 'sansevieria-trifasciata', latin: 'Sansevieria trifasciata', common: ['snake plant'], syn: ["mother-in-law's tongue"] },
    { id: 'solanum-lycopersicum', latin: 'Solanum lycopersicum', common: ['tomato'], syn: ['garden tomato'] },
    { id: 'solanum-melongena', latin: 'Solanum melongena', common: ['eggplant', 'aubergine'], syn: ['brinjal'] },
    { id: 'solanum-tuberosum', latin: 'Solanum tuberosum', common: ['potato'], syn: ['white potato'] },
    { id: 'spathiphyllum-wallisii', latin: 'Spathiphyllum wallisii', common: ['peace lily'], syn: ['spathiphyllum'] },
    { id: 'spinacia-oleracea', latin: 'Spinacia oleracea', common: ['spinach'], syn: ['garden spinach'] },
    { id: 'thymus-vulgaris', latin: 'Thymus vulgaris', common: ['thyme'], syn: ['common thyme'] },
    { id: 'tradescantia-zebrina', latin: 'Tradescantia zebrina', common: ['wandering dude'], syn: ['inch plant'] },
    { id: 'vaccinium-corymbosum', latin: 'Vaccinium corymbosum', common: ['blueberry'], syn: ['highbush blueberry'] },
    { id: 'vitis-vinifera', latin: 'Vitis vinifera', common: ['grape', 'grapevine'], syn: ['wine grape'] },
    { id: 'zea-mays', latin: 'Zea mays', common: ['corn', 'maize'], syn: ['sweet corn'] },
    { id: 'zamioculcas-zamiifolia', latin: 'Zamioculcas zamiifolia', common: ['zz plant'], syn: ['zanzibar gem'] },
  ],
};
