/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DotwellKnownNostrDotjsonRouteImport } from './routes/[.]well-known/nostr[.]json'
import { Route as GamesProjectZomboidRouteImport } from './routes/games.project-zomboid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownNostrDotjsonRoute =
  DotwellKnownNostrDotjsonRouteImport.update({
    id: '/.well-known/nostr.json',
    path: '/.well-known/nostr.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const GamesProjectZomboidRoute = GamesProjectZomboidRouteImport.update({
  id: '/games/project-zomboid',
  path: '/games/project-zomboid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/.well-known/nostr.json': typeof DotwellKnownNostrDotjsonRoute
  '/games/project-zomboid': typeof GamesProjectZomboidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/.well-known/nostr.json': typeof DotwellKnownNostrDotjsonRoute
  '/games/project-zomboid': typeof GamesProjectZomboidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/.well-known/nostr.json': typeof DotwellKnownNostrDotjsonRoute
  '/games/project-zomboid': typeof GamesProjectZomboidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/.well-known/nostr.json' | '/games/project-zomboid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/.well-known/nostr.json' | '/games/project-zomboid'
  id: '__root__' | '/' | '/.well-known/nostr.json' | '/games/project-zomboid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DotwellKnownNostrDotjsonRoute: typeof DotwellKnownNostrDotjsonRoute
  GamesProjectZomboidRoute: typeof GamesProjectZomboidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/nostr.json': {
      id: '/.well-known/nostr.json'
      path: '/.well-known/nostr.json'
      fullPath: '/.well-known/nostr.json'
      preLoaderRoute: typeof DotwellKnownNostrDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/project-zomboid': {
      id: '/games/project-zomboid'
      path: '/games/project-zomboid'
      fullPath: '/games/project-zomboid'
      preLoaderRoute: typeof GamesProjectZomboidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DotwellKnownNostrDotjsonRoute: DotwellKnownNostrDotjsonRoute,
  GamesProjectZomboidRoute: GamesProjectZomboidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
